[bindings.kotlin]
package_name = "com.osmtilecore"
cdylib_name = "osm_tile_core"
android = true
generate_immutable_records = true

[bindings.swift]
module_name = "OsmTileCore"
ffi_module_name = "OsmTileCoreFFI"
cdylib_name = "osm_tile_core"
generate_immutable_records = true
generate_codable_conformance = true
