// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(OsmTileCoreFFI)
import OsmTileCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_osm_tile_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_osm_tile_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOsmTileCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Main entry point for Android and iOS apps.
 *
 * Create one instance per map screen or per application. The object keeps a
 * cache-first tile source plus an in-memory marker store. `loadTile` is
 * synchronous in v1 and blocks on an internal Tokio runtime, so call it from a
 * background thread, coroutine dispatcher, or Swift task instead of the UI
 * thread.
 */
public protocol OsmTileCoreProtocol: AnyObject, Sendable {
    
    /**
     * Clears all markers from the Rust marker store.
     */
    func clearMarkers() throws 
    
    /**
     * Clusters every marker loaded into Rust for the given zoom.
     *
     * This ignores the current viewport but still respects each marker's zoom
     * visibility range.
     */
    func clusteredAll(zoom: Int64) throws  -> [MobileMarkerRenderItem]
    
    /**
     * Returns marker and cluster render items visible in the current viewport.
     *
     * Rust performs simple grid-based clustering in WebMercator pixel space.
     * The UI should render markers and clusters using its own icons and views.
     */
    func clusteredMarkers() throws  -> [MobileMarkerRenderItem]
    
    /**
     * Loads a map tile as raw image bytes.
     *
     * The method first checks the local offline cache. If the tile is missing,
     * it downloads the tile from the configured tile server, saves it to cache,
     * and returns the image bytes. Do not call this from the UI thread.
     */
    func loadTile(z: Int64, x: Int64, y: Int64) throws  -> Data
    
    /**
     * Removes one marker from the Rust marker store.
     */
    func removeMarker(id: Int64) throws 
    
    /**
     * Replaces all markers currently loaded into Rust.
     *
     * Use this when the app has a complete offline marker set or wants to reset
     * the working set after a new server query.
     */
    func replaceMarkers(markers: [MobileMarker]) throws 
    
    /**
     * Updates the current map viewport used by `visibleMarkers` and `clusteredMarkers`.
     */
    func setViewport(viewport: MobileViewport) throws 
    
    /**
     * Adds or updates markers by id.
     *
     * This is useful when the app loads markers page-by-page or bbox-by-bbox
     * from a backend. If the same id appears more than once, the last marker wins.
     */
    func upsertMarkers(markers: [MobileMarker]) throws 
    
    /**
     * Returns markers visible in the current viewport.
     *
     * The result is filtered by bbox and marker zoom range, then sorted by id
     * for stable rendering.
     */
    func visibleMarkers() throws  -> [MobileMarker]
    
}
/**
 * Main entry point for Android and iOS apps.
 *
 * Create one instance per map screen or per application. The object keeps a
 * cache-first tile source plus an in-memory marker store. `loadTile` is
 * synchronous in v1 and blocks on an internal Tokio runtime, so call it from a
 * background thread, coroutine dispatcher, or Swift task instead of the UI
 * thread.
 */
open class OsmTileCore: OsmTileCoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_osm_tile_core_fn_clone_osmtilecore(self.handle, $0) }
    }
    /**
     * Creates a tile engine with cache-first behavior.
     *
     * `tile_url_template` must contain `{z}`, `{x}`, and `{y}` placeholders,
     * for example `http://10.0.2.2:8080/tile/{z}/{x}/{y}.png` on the Android
     * emulator. `cache_dir` should be inside the app-private storage directory.
     */
public convenience init(tileUrlTemplate: String, cacheDir: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_constructor_osmtilecore_new(
        FfiConverterString.lower(tileUrlTemplate),
        FfiConverterString.lower(cacheDir),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_osm_tile_core_fn_free_osmtilecore(handle, $0) }
    }

    

    
    /**
     * Clears all markers from the Rust marker store.
     */
open func clearMarkers()throws   {try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_clear_markers(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Clusters every marker loaded into Rust for the given zoom.
     *
     * This ignores the current viewport but still respects each marker's zoom
     * visibility range.
     */
open func clusteredAll(zoom: Int64)throws  -> [MobileMarkerRenderItem]  {
    return try  FfiConverterSequenceTypeMobileMarkerRenderItem.lift(try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_clustered_all(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(zoom),$0
    )
})
}
    
    /**
     * Returns marker and cluster render items visible in the current viewport.
     *
     * Rust performs simple grid-based clustering in WebMercator pixel space.
     * The UI should render markers and clusters using its own icons and views.
     */
open func clusteredMarkers()throws  -> [MobileMarkerRenderItem]  {
    return try  FfiConverterSequenceTypeMobileMarkerRenderItem.lift(try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_clustered_markers(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Loads a map tile as raw image bytes.
     *
     * The method first checks the local offline cache. If the tile is missing,
     * it downloads the tile from the configured tile server, saves it to cache,
     * and returns the image bytes. Do not call this from the UI thread.
     */
open func loadTile(z: Int64, x: Int64, y: Int64)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_load_tile(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(z),
        FfiConverterInt64.lower(x),
        FfiConverterInt64.lower(y),$0
    )
})
}
    
    /**
     * Removes one marker from the Rust marker store.
     */
open func removeMarker(id: Int64)throws   {try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_remove_marker(
            self.uniffiCloneHandle(),
        FfiConverterInt64.lower(id),$0
    )
}
}
    
    /**
     * Replaces all markers currently loaded into Rust.
     *
     * Use this when the app has a complete offline marker set or wants to reset
     * the working set after a new server query.
     */
open func replaceMarkers(markers: [MobileMarker])throws   {try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_replace_markers(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeMobileMarker.lower(markers),$0
    )
}
}
    
    /**
     * Updates the current map viewport used by `visibleMarkers` and `clusteredMarkers`.
     */
open func setViewport(viewport: MobileViewport)throws   {try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_set_viewport(
            self.uniffiCloneHandle(),
        FfiConverterTypeMobileViewport_lower(viewport),$0
    )
}
}
    
    /**
     * Adds or updates markers by id.
     *
     * This is useful when the app loads markers page-by-page or bbox-by-bbox
     * from a backend. If the same id appears more than once, the last marker wins.
     */
open func upsertMarkers(markers: [MobileMarker])throws   {try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_upsert_markers(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeMobileMarker.lower(markers),$0
    )
}
}
    
    /**
     * Returns markers visible in the current viewport.
     *
     * The result is filtered by bbox and marker zoom range, then sorted by id
     * for stable rendering.
     */
open func visibleMarkers()throws  -> [MobileMarker]  {
    return try  FfiConverterSequenceTypeMobileMarker.lift(try rustCallWithError(FfiConverterTypeOsmTileCoreError_lift) {
    uniffi_osm_tile_core_fn_method_osmtilecore_visible_markers(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOsmTileCore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = OsmTileCore

    public static func lift(_ handle: UInt64) throws -> OsmTileCore {
        return OsmTileCore(unsafeFromHandle: handle)
    }

    public static func lower(_ value: OsmTileCore) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OsmTileCore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: OsmTileCore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOsmTileCore_lift(_ handle: UInt64) throws -> OsmTileCore {
    return try FfiConverterTypeOsmTileCore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOsmTileCore_lower(_ value: OsmTileCore) -> UInt64 {
    return FfiConverterTypeOsmTileCore.lower(value)
}




/**
 * A point marker known to the Rust core.
 *
 * The UI still decides how the marker looks. Rust stores coordinates, kind,
 * and zoom visibility so it can return only the markers relevant to the
 * current viewport.
 */
public struct MobileMarker: Equatable, Hashable, Codable {
    /**
     * Stable marker id. Use the same id when updating a marker with `upsertMarkers`.
     */
    public let id: Int64
    /**
     * Marker latitude in `-90..=90`.
     */
    public let lat: Double
    /**
     * Marker longitude in `-180..=180`.
     */
    public let lon: Double
    /**
     * Domain-specific marker category, for example `cafe`, `hotel`, or `vehicle`.
     */
    public let kind: String
    /**
     * First zoom level where this marker should be visible.
     */
    public let minZoom: Int64
    /**
     * Last zoom level where this marker should be visible.
     */
    public let maxZoom: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable marker id. Use the same id when updating a marker with `upsertMarkers`.
         */id: Int64, 
        /**
         * Marker latitude in `-90..=90`.
         */lat: Double, 
        /**
         * Marker longitude in `-180..=180`.
         */lon: Double, 
        /**
         * Domain-specific marker category, for example `cafe`, `hotel`, or `vehicle`.
         */kind: String, 
        /**
         * First zoom level where this marker should be visible.
         */minZoom: Int64, 
        /**
         * Last zoom level where this marker should be visible.
         */maxZoom: Int64) {
        self.id = id
        self.lat = lat
        self.lon = lon
        self.kind = kind
        self.minZoom = minZoom
        self.maxZoom = maxZoom
    }

    

    
}

#if compiler(>=6)
extension MobileMarker: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileMarker: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileMarker {
        return
            try MobileMarker(
                id: FfiConverterInt64.read(from: &buf), 
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                minZoom: FfiConverterInt64.read(from: &buf), 
                maxZoom: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileMarker, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterInt64.write(value.minZoom, into: &buf)
        FfiConverterInt64.write(value.maxZoom, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarker_lift(_ buf: RustBuffer) throws -> MobileMarker {
    return try FfiConverterTypeMobileMarker.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarker_lower(_ value: MobileMarker) -> RustBuffer {
    return FfiConverterTypeMobileMarker.lower(value)
}


/**
 * A cluster returned by Rust for rendering on the current map.
 *
 * The cluster coordinate is the average coordinate of all markers in the
 * cluster. The mobile UI decides which icon, text, and interaction to use.
 */
public struct MobileMarkerCluster: Equatable, Hashable, Codable {
    /**
     * Stable cluster id for the current zoom/grid cell.
     */
    public let id: String
    /**
     * Cluster latitude.
     */
    public let lat: Double
    /**
     * Cluster longitude.
     */
    public let lon: Double
    /**
     * Number of markers represented by this cluster.
     */
    public let count: Int64
    /**
     * Marker ids included in the cluster.
     */
    public let markerIds: [Int64]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable cluster id for the current zoom/grid cell.
         */id: String, 
        /**
         * Cluster latitude.
         */lat: Double, 
        /**
         * Cluster longitude.
         */lon: Double, 
        /**
         * Number of markers represented by this cluster.
         */count: Int64, 
        /**
         * Marker ids included in the cluster.
         */markerIds: [Int64]) {
        self.id = id
        self.lat = lat
        self.lon = lon
        self.count = count
        self.markerIds = markerIds
    }

    

    
}

#if compiler(>=6)
extension MobileMarkerCluster: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileMarkerCluster: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileMarkerCluster {
        return
            try MobileMarkerCluster(
                id: FfiConverterString.read(from: &buf), 
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf), 
                count: FfiConverterInt64.read(from: &buf), 
                markerIds: FfiConverterSequenceInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileMarkerCluster, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
        FfiConverterInt64.write(value.count, into: &buf)
        FfiConverterSequenceInt64.write(value.markerIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarkerCluster_lift(_ buf: RustBuffer) throws -> MobileMarkerCluster {
    return try FfiConverterTypeMobileMarkerCluster.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarkerCluster_lower(_ value: MobileMarkerCluster) -> RustBuffer {
    return FfiConverterTypeMobileMarkerCluster.lower(value)
}


/**
 * A render item returned by `clusteredMarkers` or `clusteredAll`.
 *
 * UniFFI records are simpler for Kotlin and Swift when the shape is stable, so
 * this type uses `item_type` plus optional `marker`/`cluster` payloads.
 */
public struct MobileMarkerRenderItem: Equatable, Hashable, Codable {
    /**
     * Tells the UI which payload field to read.
     */
    public let itemType: MobileRenderItemType
    /**
     * Present when `item_type == Marker`.
     */
    public let marker: MobileMarker?
    /**
     * Present when `item_type == Cluster`.
     */
    public let cluster: MobileMarkerCluster?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Tells the UI which payload field to read.
         */itemType: MobileRenderItemType, 
        /**
         * Present when `item_type == Marker`.
         */marker: MobileMarker?, 
        /**
         * Present when `item_type == Cluster`.
         */cluster: MobileMarkerCluster?) {
        self.itemType = itemType
        self.marker = marker
        self.cluster = cluster
    }

    

    
}

#if compiler(>=6)
extension MobileMarkerRenderItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileMarkerRenderItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileMarkerRenderItem {
        return
            try MobileMarkerRenderItem(
                itemType: FfiConverterTypeMobileRenderItemType.read(from: &buf), 
                marker: FfiConverterOptionTypeMobileMarker.read(from: &buf), 
                cluster: FfiConverterOptionTypeMobileMarkerCluster.read(from: &buf)
        )
    }

    public static func write(_ value: MobileMarkerRenderItem, into buf: inout [UInt8]) {
        FfiConverterTypeMobileRenderItemType.write(value.itemType, into: &buf)
        FfiConverterOptionTypeMobileMarker.write(value.marker, into: &buf)
        FfiConverterOptionTypeMobileMarkerCluster.write(value.cluster, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarkerRenderItem_lift(_ buf: RustBuffer) throws -> MobileMarkerRenderItem {
    return try FfiConverterTypeMobileMarkerRenderItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileMarkerRenderItem_lower(_ value: MobileMarkerRenderItem) -> RustBuffer {
    return FfiConverterTypeMobileMarkerRenderItem.lower(value)
}


/**
 * The currently visible map rectangle and zoom level.
 *
 * Pass this from Android or iOS whenever the map camera changes enough that
 * visible markers or clusters should be recalculated.
 */
public struct MobileViewport: Equatable, Hashable, Codable {
    /**
     * Southern latitude of the visible map area.
     */
    public let south: Double
    /**
     * Western longitude of the visible map area.
     *
     * If `west > east`, the bounds cross the antimeridian.
     */
    public let west: Double
    /**
     * Northern latitude of the visible map area.
     */
    public let north: Double
    /**
     * Eastern longitude of the visible map area.
     */
    public let east: Double
    /**
     * Integer map zoom. The supported range is `0..=30`.
     */
    public let zoom: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Southern latitude of the visible map area.
         */south: Double, 
        /**
         * Western longitude of the visible map area.
         *
         * If `west > east`, the bounds cross the antimeridian.
         */west: Double, 
        /**
         * Northern latitude of the visible map area.
         */north: Double, 
        /**
         * Eastern longitude of the visible map area.
         */east: Double, 
        /**
         * Integer map zoom. The supported range is `0..=30`.
         */zoom: Int64) {
        self.south = south
        self.west = west
        self.north = north
        self.east = east
        self.zoom = zoom
    }

    

    
}

#if compiler(>=6)
extension MobileViewport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileViewport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileViewport {
        return
            try MobileViewport(
                south: FfiConverterDouble.read(from: &buf), 
                west: FfiConverterDouble.read(from: &buf), 
                north: FfiConverterDouble.read(from: &buf), 
                east: FfiConverterDouble.read(from: &buf), 
                zoom: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileViewport, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.south, into: &buf)
        FfiConverterDouble.write(value.west, into: &buf)
        FfiConverterDouble.write(value.north, into: &buf)
        FfiConverterDouble.write(value.east, into: &buf)
        FfiConverterInt64.write(value.zoom, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileViewport_lift(_ buf: RustBuffer) throws -> MobileViewport {
    return try FfiConverterTypeMobileViewport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileViewport_lower(_ value: MobileViewport) -> RustBuffer {
    return FfiConverterTypeMobileViewport.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Identifies which optional payload is present in `MobileMarkerRenderItem`.
 */

public enum MobileRenderItemType: Equatable, Hashable, Codable {
    
    /**
     * `marker` is present and `cluster` is empty.
     */
    case marker
    /**
     * `cluster` is present and `marker` is empty.
     */
    case cluster





}

#if compiler(>=6)
extension MobileRenderItemType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileRenderItemType: FfiConverterRustBuffer {
    typealias SwiftType = MobileRenderItemType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileRenderItemType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .marker
        
        case 2: return .cluster
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileRenderItemType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .marker:
            writeInt(&buf, Int32(1))
        
        
        case .cluster:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileRenderItemType_lift(_ buf: RustBuffer) throws -> MobileRenderItemType {
    return try FfiConverterTypeMobileRenderItemType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileRenderItemType_lower(_ value: MobileRenderItemType) -> RustBuffer {
    return FfiConverterTypeMobileRenderItemType.lower(value)
}



/**
 * Error type exposed to Kotlin and Swift callers.
 *
 * The `details` field is safe to display in logs and developer diagnostics.
 */
public enum OsmTileCoreError: Swift.Error, Equatable, Hashable, Codable, Foundation.LocalizedError {

    
    
    /**
     * The caller passed invalid coordinates, zoom, ids, or URL template.
     */
    case InvalidInput(details: String
    )
    /**
     * The tile cache could not read or write local files.
     */
    case Cache(details: String
    )
    /**
     * The tile server request failed or returned a non-success HTTP status.
     */
    case Network(details: String
    )
    /**
     * The map state is not ready for the requested operation.
     */
    case State(details: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension OsmTileCoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOsmTileCoreError: FfiConverterRustBuffer {
    typealias SwiftType = OsmTileCoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OsmTileCoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            details: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Cache(
            details: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Network(
            details: try FfiConverterString.read(from: &buf)
            )
        case 4: return .State(
            details: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OsmTileCoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidInput(details):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(details, into: &buf)
            
        
        case let .Cache(details):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(details, into: &buf)
            
        
        case let .Network(details):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(details, into: &buf)
            
        
        case let .State(details):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(details, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOsmTileCoreError_lift(_ buf: RustBuffer) throws -> OsmTileCoreError {
    return try FfiConverterTypeOsmTileCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOsmTileCoreError_lower(_ value: OsmTileCoreError) -> RustBuffer {
    return FfiConverterTypeOsmTileCoreError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMobileMarker: FfiConverterRustBuffer {
    typealias SwiftType = MobileMarker?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMobileMarker.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMobileMarker.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMobileMarkerCluster: FfiConverterRustBuffer {
    typealias SwiftType = MobileMarkerCluster?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMobileMarkerCluster.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMobileMarkerCluster.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt64: FfiConverterRustBuffer {
    typealias SwiftType = [Int64]

    public static func write(_ value: [Int64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int64] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMobileMarker: FfiConverterRustBuffer {
    typealias SwiftType = [MobileMarker]

    public static func write(_ value: [MobileMarker], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMobileMarker.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MobileMarker] {
        let len: Int32 = try readInt(&buf)
        var seq = [MobileMarker]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMobileMarker.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMobileMarkerRenderItem: FfiConverterRustBuffer {
    typealias SwiftType = [MobileMarkerRenderItem]

    public static func write(_ value: [MobileMarkerRenderItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMobileMarkerRenderItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MobileMarkerRenderItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [MobileMarkerRenderItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMobileMarkerRenderItem.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_osm_tile_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_clear_markers() != 41979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_clustered_all() != 62518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_clustered_markers() != 14318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_load_tile() != 53716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_remove_marker() != 42478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_replace_markers() != 52436) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_set_viewport() != 4635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_upsert_markers() != 38029) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_method_osmtilecore_visible_markers() != 61696) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_osm_tile_core_checksum_constructor_osmtilecore_new() != 51926) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOsmTileCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all